@HiveServer_HostAddress         = http://localhost:5071/api
@HiveServer_HostAddress_Auth    = http://localhost:5071/api/auth
@HiveServer_HostAddress_Account = http://localhost:5071/api/account

### 가입
POST {{HiveServer_HostAddress}}/Register/
Content-Type: application/json

{
  "Account":"mlxg",
  "Password":"mlt"
}

### 로그인
POST {{HiveServer_HostAddress}}/Login/
Content-Type: application/json

{
  "Account":"mlxg",
  "Password":"mlt"
}

### 토큰 인증
POST {{HiveServer_HostAddress}}/VerifyToken/
Content-Type: application/json

{
  "Account":"mlxg",
  "Token":"test_test|test_test|test_test|test_test|test_test|test_test|test"
}

### 토큰 갱신
POST {{HiveServer_HostAddress}}/RefreshToken/
Content-Type: application/json

{
  "Account":"mlxg",
  "OldToken":"test_test|test_test|test_test|test_test|test_test|test_test|test"
}
