use game_db;

CREATE TABLE IF NOT EXISTS player
(
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT UNIQUE,
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `last_login_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mail
(
  `owner_id` BIGINT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS friend
(
  `owner_id` BIGINT AUTO_INCREMENT PRIMARY KEY
);
